### ISSUE TITLE
모집글 entity 생성

### ISSUE THREAD

**Issue by yujin9747** [HCU-4400WON/hot6#1]
**Description**
- 모집글 entity 생성 및 연관관계 설정

**Todo**
- [x] 모집글 entity 작성
- [x] 스터디 entity 작성
- [x] 멘토링 entity 작성
- [x] 프로젝트 entity 작성
- [x] 프로젝트, 스터디, 멘토링 생성 메소드 작성
- [x] post - author 필드 양방향 매핑 메소드 작성

**ETC**
- Post 상속 전략: single table 전략에서 joined 전략으로 변경 -> 컬럼 개수가 너무 많아서
- Post 유형 @DiscriminatorValue 축약어로 지정함 (Project : P, Mentoring : M, Study : S)
