### ISSUE TITLE
version2 엔티티 수정

### ISSUE THREAD

**Issue by yujin9747** [HCU-4400WON/hot6#134]
** Todo **
- [] 포스터 엔티티 추가
- [] 멤버 엔티티에 리스트로 연관관계 가지는 필드 추가
- [] 포스트 엔티티 수정
- [] 썸네일 엔티티 추가
- [] 포지션 엔티티 추가 - 기존 이넘 방식에서 엔티티로 수정
- [] 아카이브 엔티티 추가
