### ISSUE TITLE
Post - Project, Study 생성자

### ISSUE THREAD

**Issue by yujin9747** [HCU-4400WON/hot6#14]
**Description**
- issue 12번에서 구현한 Mentoring 생성자를 Project, Study 엔티티에도 적용

**Todo**
- [ ] Project 생성자 with @Builder
- [ ] Study 생성자 with @Builder
- [ ] Project 생성자 테스트 코드 작성
- [ ] Study 생성자 테스트 코드 작성

**ETC**
