### ISSUE TITLE
모집글 페이지 , 메인 페이지 프론트 기능 구현

### ISSUE THREAD

**Issue by ohinhyuk** [HCU-4400WON/hot6#30]
**Description**
- 가상 데이터 만들고 이를 통해 기능 구현

**ToDo**
- [x]  메인 / 가상 데이터 만들기
- [x]  메인 / 가상 데이터로 수정
- [x]  모집글 / 가상 데이터 만들기
- [x]  모집글 / 가상 데이터로 수정
- [x]  모집글 / 필터링 , 정렬 , 로딩 기능 구현
