### ISSUE TITLE
Post 및 자식 클래스 nullable 설정

### ISSUE THREAD

**Issue by yujin9747** [HCU-4400WON/hot6#6]
**Todo**
- [x] post, study, project, mentoring 필드 nullable 속성 추가하기
- [x] Member @Getter 추가
- [x] 메소드 이름 변경 : changeAuthor -> registerAuthor
